name: Custom Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Branch name to checkout"
        required: true
      title:
        description: "Title"
        required: true
      desc:
        description: "Description"
        required: true
      thumbnail_url:
        description: "Thumbnail URL"
        required: true
      video_url:
        description: "Video URL"
        required: true
      video_id:
        description: "Video ID"
        required: true
        

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Issue
        uses: actions/github-script@v6
        with:
          script: |
            const inputs = context.payload.inputs;
            const { title, desc, thumbnail_url, video_url, video_id } = inputs;
            const issueTitle = `${title} - ${video_id}`;
            const issueBody = `
            **Title**: ${title}
            **Description**: ${desc}
            **Thumbnail URL**: ${thumbnail_url}
            **Video URL**: ${video_url}
            `;
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
            });
            
            core.setOutput('issue_number', issue.data.number);

  modify-files:
    runs-on: ubuntu-latest
    needs: create-issue
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch_name }}

      - name: Modify title.txt
        run: echo "${{ github.event.inputs.title }}" > video/title.txt

      - name: Modify desc.txt
        run: echo "${{ github.event.inputs.desc }}" > video/description.txt

      - name: Modify thumbnail.txt
        run: echo "${{ github.event.inputs.thumbnail_url }}" > video/thumbnail_link.txt

      - name: Modify video_url.txt
        run: echo "${{ github.event.inputs.video_url }}" > video/video_link.txt

      - name: Modify video_id.txt
        run: echo "${{ github.event.inputs.video_id }}" > video_id.txt

      - name: Commit changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git add video video_id.txt
          git commit -m "Uploading ${{ github.event.inputs.video_id }} to ${{ github.event.inputs.branch_name }}"
          git push origin ${{ github.event.inputs.branch_name }}
